services:
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: reporter
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - "8886:3306"
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: pma
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8899:80"

  nestjs:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nest-app
    depends_on:
      - db
    ports:
      - "3000:3000"
    command: npm run start:dev
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-app
    ports:
      - "5173:80"
    depends_on:
      - nestjs

volumes:
  dbdata:
